# extended resource name which the device plugin serves
resourceName: hostpath-device.k8s.io/sample
# filename of unix socket to be created that the device plugin listens
socketName: hostpath-device.k8s.io-sample.sock
# the number of extended resource that the device plugin serves
numDevices: 100
hostPath: 
  path: /sample
  type: Directory
volumeMount:
  mountPath: /sample
  readOnly: false
