apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hostpath-sample-device-plugin
namePrefix: hostpath-sample-device-plugin-

commonLabels:
  app.kubernetes.io/name: hostpath-sample-device-plugin

resources:
- namespace.yaml
- device-plugin/
- webhook/

configMapGenerator:
- name: hostpath-sample-device-config
  files:
  - config.yaml

vars:
- name: CERTIFICATE_NAMESPACE
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
- name: SERVICE_NAMESPACE
  objref:
    kind: Service
    version: v1
    name: webhook-service
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: webhook-service
