apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- hostpath-device-plugin.yaml

configMapGenerator:
- name: hostpath-sample-device-config
  files:
  - config.yaml
