apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hostpath-sample-device-plugin
namePrefix: hostpath-sample-device-plugin-

commonLabels:
  app.kubernetes.io/name: hostpath-sample-device-plugin

resources:
- namespace.yaml
- device-plugin/
- webhook/

configMapGenerator:
- files:
  - config.yaml
  name: hostpath-sample-device-config

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: CERTIFICATE_NAMESPACE
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref: {}
  name: CERTIFICATE_NAME
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref:
    fieldPath: metadata.namespace
  name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: webhook-service
    version: v1
- fieldref: {}
  name: SERVICE_NAME
  objref:
    kind: Service
    name: webhook-service
    version: v1
images:
- name: k8s-hostpath-device-plugin
  newName: ghcr.io/everpeace/k8s-hostpath-device-plugin
  newTag: latest
