run:
  tests: false
  exclude-dirs:
  - .dev/
output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters:
  enable:
    - govet
    - gofmt
    - goimports
    - unconvert
    - misspell
    - prealloc
  fast: false
