apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
- certificate.yaml
- service.yaml
- deployment.yaml
- mutatingwebhookconfiguration.yaml
configurations:
- kustomizeconfig.yaml
