# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags-ignore: [ "**" ]
    paths-ignore: [ "**.md" ]
  pull_request:
    types: [opened, synchronize]
    paths-ignore: [ "**.md" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Get dependencies
      run: go mod download
    - name: Get Devtools
      run: make setup
    - name: Lint
      run : make lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Check out
      uses: actions/checkout@v3
    - name: Get dependencies
      run: go mod download
    - name: Get Devtools
      run: make setup
    - name: Unit Test
      run: make test

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Check out
      uses: actions/checkout@v3
    - name: Get dependencies
      run: go mod download
    - name: Get Devtools
      run: make setup
    - name: E2E Test
      run: make e2e-test

  validate-goreleaser-yml:
    name: Validate .goreleaser.yml
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Check out
      uses: actions/checkout@v3
    - name: Validate
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --snapshot --skip-publish --rm-dist --debug
