name: Release By Tagged Manually
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release Binaries
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      RELEASE: "true"
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Release
      uses: ./.github/actions/release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
